import {
  Users,
  Calendar,
  BarChart3,
  Sparkles,
  Mic2,
  Shield,
  Crown,
  Zap,
} from '../../components/icons'

// Feature comparison for the 5-tier table
export const FEATURES = [
  {
    name: 'Squads',
    free: '1 squad',
    premium: '5 squads',
    squadLeader: 'Illimité',
    team: 'Illimité',
    club: 'Illimité',
    icon: Users,
    highlight: true,
  },
  {
    name: 'Membres max',
    free: '5',
    premium: '20',
    squadLeader: '50',
    team: '75',
    club: '100',
    icon: Users,
    highlight: true,
  },
  {
    name: 'Sessions par semaine',
    free: '2',
    premium: 'Illimitées',
    squadLeader: 'Illimitées',
    team: 'Illimitées',
    club: 'Illimitées',
    icon: Calendar,
    highlight: true,
  },
  {
    name: 'Historique sessions',
    free: '7 jours',
    premium: '90 jours',
    squadLeader: 'Illimité',
    team: 'Illimité',
    club: 'Illimité',
    icon: Calendar,
    highlight: true,
  },
  {
    name: 'Chat complet (GIF, voice, polls)',
    free: false,
    premium: true,
    squadLeader: true,
    team: true,
    club: true,
    icon: Sparkles,
    highlight: true,
  },
  {
    name: 'Stats & Analytics',
    free: 'Basiques',
    premium: 'Avancées',
    squadLeader: 'Avancées',
    team: 'Cross-squad',
    club: 'Cross-squad',
    icon: BarChart3,
    highlight: true,
  },
  {
    name: 'IA Coach',
    free: false,
    premium: 'Basique',
    squadLeader: 'Avancé',
    team: 'Avancé',
    club: 'Avancé',
    icon: Sparkles,
    highlight: true,
  },
  {
    name: 'Audio HD Party',
    free: false,
    premium: false,
    squadLeader: true,
    team: true,
    club: true,
    icon: Mic2,
    highlight: false,
  },
  {
    name: 'Rôles avancés (IGL, Coach, Shotcaller)',
    free: false,
    premium: false,
    squadLeader: true,
    team: true,
    club: true,
    icon: Shield,
    highlight: false,
  },
  {
    name: 'Export calendrier',
    free: false,
    premium: false,
    squadLeader: true,
    team: true,
    club: true,
    icon: Calendar,
    highlight: false,
  },
  {
    name: 'Sessions récurrentes',
    free: false,
    premium: false,
    squadLeader: true,
    team: true,
    club: true,
    icon: Calendar,
    highlight: false,
  },
  {
    name: 'Dashboard analytics équipe',
    free: false,
    premium: false,
    squadLeader: true,
    team: true,
    club: true,
    icon: BarChart3,
    highlight: false,
  },
  {
    name: 'Priorité matchmaking',
    free: false,
    premium: false,
    squadLeader: true,
    team: true,
    club: true,
    icon: Zap,
    highlight: false,
  },
  {
    name: 'Dashboard multi-squads',
    free: false,
    premium: false,
    squadLeader: false,
    team: true,
    club: true,
    icon: BarChart3,
    highlight: false,
  },
  {
    name: 'Branding personnalisé',
    free: false,
    premium: false,
    squadLeader: false,
    team: false,
    club: true,
    icon: Crown,
    highlight: false,
  },
  {
    name: 'API webhooks',
    free: false,
    premium: false,
    squadLeader: false,
    team: false,
    club: true,
    icon: Zap,
    highlight: false,
  },
  {
    name: 'Support prioritaire',
    free: 'Sous 48h',
    premium: 'Sous 24h',
    squadLeader: 'Sous 12h',
    team: 'Sous 8h',
    club: 'Sous 4h',
    icon: Shield,
    highlight: true,
  },
  {
    name: 'Badge exclusif',
    free: false,
    premium: 'Violet',
    squadLeader: 'Doré',
    team: 'Bleu',
    club: 'Doré',
    icon: Crown,
    highlight: false,
  },
]

export const TESTIMONIALS = [
  {
    name: 'Le capitaine de squad',
    squad: 'Exemple : squad ranked',
    memberSince: 'Cas d\'usage type',
    text: "Plus personne n'oublie les sessions. Le coach IA analyse tes habitudes et te propose les meilleurs créneaux pour ta squad.",
    avatarType: 'alex' as const,
  },
  {
    name: 'La joueuse compétitive',
    squad: 'Exemple : squad féminine',
    memberSince: 'Cas d\'usage type',
    text: "L'audio HD fait la différence en ranked. Les stats détaillées montrent qui clutch le plus — et ça motive tout le monde.",
    avatarType: 'marie' as const,
  },
  {
    name: 'Le multi-squad',
    squad: 'Exemple : plusieurs jeux',
    memberSince: 'Cas d\'usage type',
    text: "Gérer plusieurs squads sur différents jeux, c'est le vrai avantage. Un seul dashboard pour tout organiser.",
    avatarType: 'lucas' as const,
  },
]

export const FAQ = [
  {
    q: 'Je peux annuler quand je veux ?',
    a: "Oui ! Tu peux annuler ton abonnement à tout moment depuis ton profil. Tu garderas l'accès jusqu'à la fin de ta période payée. Zéro engagement, zéro frais cachés.",
  },
  {
    q: "C'est quoi la différence entre Premium et Squad Leader ?",
    a: 'Premium est pour les joueurs réguliers qui veulent plus de squads et de features. Squad Leader est pour les capitaines qui gèrent des équipes — avec dashboard analytics, sessions récurrentes, audio HD et rôles avancés.',
  },
  {
    q: "Le tier Team, c'est pour qui ?",
    a: "Le Team est pour les équipes structurées qui ont besoin d'un dashboard multi-squads, de stats cross-squad et de gérer jusqu'à 75 membres. Idéal pour les guildes et clans organisés.",
  },
  {
    q: "Le tier Club, c'est pour qui ?",
    a: "Le Club est conçu pour les structures esport et les organisations qui gèrent plusieurs équipes. Tu as du branding personnalisé, des API webhooks, un support prioritaire sous 4h et une facturation entreprise. Contacte-nous pour un devis sur mesure.",
  },
  {
    q: "Y a-t-il une période d'essai ?",
    a: "Oui ! Tu bénéficies de 7 jours d'essai gratuit sans carte bancaire. À la fin de l'essai, tu choisis ton plan. On offre aussi une garantie satisfait ou remboursé de 30 jours.",
  },
  {
    q: 'Comment demander un remboursement ?',
    a: "Garantie satisfait ou remboursé de 30 jours, sans condition et sans justification. Contacte-nous via le formulaire dans tes paramètres (section Abonnement), et on te rembourse sous 48h par virement. Tu peux aussi passer par le support dans la page Aide.",
  },
]
