import {
  Users,
  Calendar,
  BarChart3,
  Sparkles,
  Mic2,
  Shield,
  Crown,
  Zap,
} from '../../components/icons'

// Feature comparison for the 4-tier table
export const FEATURES = [
  {
    name: 'Squads',
    free: '1 squad',
    premium: '5 squads',
    squadLeader: 'Illimité',
    club: 'Illimité',
    icon: Users,
    highlight: true,
  },
  {
    name: 'Sessions par semaine',
    free: '3',
    premium: 'Illimitées',
    squadLeader: 'Illimitées',
    club: 'Illimitées',
    icon: Calendar,
    highlight: true,
  },
  {
    name: 'Historique sessions',
    free: '7 jours',
    premium: '90 jours',
    squadLeader: 'Illimité',
    club: 'Illimité',
    icon: Calendar,
    highlight: true,
  },
  {
    name: 'Chat complet (GIF, voice, polls)',
    free: false,
    premium: true,
    squadLeader: true,
    club: true,
    icon: Sparkles,
    highlight: true,
  },
  {
    name: 'Stats & Analytics',
    free: 'Basiques',
    premium: 'Avancées',
    squadLeader: 'Avancées',
    club: 'Cross-squad',
    icon: BarChart3,
    highlight: true,
  },
  {
    name: 'IA Coach',
    free: false,
    premium: 'Basique',
    squadLeader: 'Avancé',
    club: 'Avancé',
    icon: Sparkles,
    highlight: true,
  },
  {
    name: 'Audio HD Party',
    free: false,
    premium: false,
    squadLeader: true,
    club: true,
    icon: Mic2,
    highlight: false,
  },
  {
    name: 'Rôles avancés (Leader, Co-leader, Modérateur)',
    free: false,
    premium: false,
    squadLeader: true,
    club: true,
    icon: Shield,
    highlight: false,
  },
  {
    name: 'Export calendrier',
    free: false,
    premium: false,
    squadLeader: true,
    club: true,
    icon: Calendar,
    highlight: false,
  },
  {
    name: 'Sessions récurrentes',
    free: false,
    premium: false,
    squadLeader: true,
    club: true,
    icon: Calendar,
    highlight: false,
  },
  {
    name: 'Dashboard analytics équipe',
    free: false,
    premium: false,
    squadLeader: true,
    club: true,
    icon: BarChart3,
    highlight: false,
  },
  {
    name: 'Priorité matchmaking',
    free: false,
    premium: false,
    squadLeader: true,
    club: true,
    icon: Zap,
    highlight: false,
  },
  {
    name: 'Dashboard multi-squads',
    free: false,
    premium: false,
    squadLeader: false,
    club: true,
    icon: BarChart3,
    highlight: false,
  },
  {
    name: 'Branding personnalisé',
    free: false,
    premium: false,
    squadLeader: false,
    club: true,
    icon: Crown,
    highlight: false,
  },
  {
    name: 'Export CSV avancé',
    free: false,
    premium: false,
    squadLeader: false,
    club: true,
    icon: Zap,
    highlight: false,
  },
  {
    name: 'Support prioritaire par email',
    free: false,
    premium: false,
    squadLeader: false,
    club: true,
    icon: Shield,
    highlight: false,
  },
  {
    name: 'Badge exclusif',
    free: false,
    premium: 'Violet',
    squadLeader: 'Doré',
    club: 'Doré',
    icon: Crown,
    highlight: false,
  },
]

export const TESTIMONIALS = [
  {
    name: 'Le capitaine de squad',
    squad: 'Exemple : squad ranked',
    memberSince: 'Cas d\'usage type',
    text: "Plus personne n'oublie les sessions. Le coach IA analyse tes habitudes et te propose les meilleurs créneaux pour ta squad.",
    avatarType: 'alex' as const,
  },
  {
    name: 'La joueuse compétitive',
    squad: 'Exemple : squad féminine',
    memberSince: 'Cas d\'usage type',
    text: "L'audio HD fait la différence en ranked. Les stats détaillées montrent qui clutch le plus — et ça motive tout le monde.",
    avatarType: 'marie' as const,
  },
  {
    name: 'Le multi-squad',
    squad: 'Exemple : plusieurs jeux',
    memberSince: 'Cas d\'usage type',
    text: "Gérer plusieurs squads sur différents jeux, c'est le vrai avantage. Un seul dashboard pour tout organiser.",
    avatarType: 'lucas' as const,
  },
]

export const FAQ = [
  {
    q: 'Je peux annuler quand je veux ?',
    a: "Oui ! Tu peux annuler ton abonnement à tout moment depuis ton profil. Tu garderas l'accès jusqu'à la fin de ta période payée.",
  },
  {
    q: "C'est quoi la différence entre Premium et Squad Leader ?",
    a: 'Premium est pour les joueurs réguliers qui veulent plus de squads et de features. Squad Leader est pour les capitaines qui gèrent des équipes — avec dashboard analytics, sessions récurrentes, audio HD et rôles avancés.',
  },
  {
    q: "Le tier Club, c'est pour qui ?",
    a: 'Le Club est conçu pour les structures esport et les organisations qui gèrent plusieurs équipes. Tu as un dashboard multi-squads, du branding personnalisé, un export CSV avancé et un support prioritaire par email.',
  },
  {
    q: "Y a-t-il une période d'essai ?",
    a: "Oui ! Tu bénéficies de 7 jours d'essai gratuit sans carte bancaire. À la fin de l'essai, tu choisis ton plan. On offre aussi une garantie satisfait ou remboursé de 30 jours.",
  },
]
