import {
  Users,
  Calendar,
  BarChart3,
  Sparkles,
  Mic2,
  Shield,
  Crown,
  Zap,
} from '../../components/icons'

// Feature comparison for the 5-tier table
export const FEATURES = [
  {
    name: 'Squads',
    description: 'Gère toutes tes équipes au même endroit',
    free: '1 squad',
    premium: '5 squads',
    squadLeader: 'Illimité',
    team: 'Illimité',
    club: 'Illimité',
    icon: Users,
    highlight: true,
  },
  {
    name: 'Membres max',
    description: 'Invite tous tes potes sans restriction',
    free: '5',
    premium: '20',
    squadLeader: '50',
    team: '75',
    club: '100',
    icon: Users,
    highlight: true,
  },
  {
    name: 'Sessions par semaine',
    description: 'Joue autant que tu veux, quand tu veux',
    free: '2',
    premium: 'Illimitées',
    squadLeader: 'Illimitées',
    team: 'Illimitées',
    club: 'Illimitées',
    icon: Calendar,
    highlight: true,
  },
  {
    name: 'Historique sessions',
    description: 'Retrouve n\'importe quelle session passée',
    free: '7 jours',
    premium: '90 jours',
    squadLeader: 'Illimité',
    team: 'Illimité',
    club: 'Illimité',
    icon: Calendar,
    highlight: true,
  },
  {
    name: 'Chat complet (GIF, voice, polls)',
    description: 'Communique avec ta squad sans quitter l\'app',
    free: false,
    premium: true,
    squadLeader: true,
    team: true,
    club: true,
    icon: Sparkles,
    highlight: true,
  },
  {
    name: 'Stats & Analytics',
    description: 'Comprends les habitudes de ta squad',
    free: 'Basiques',
    premium: 'Avancées',
    squadLeader: 'Avancées',
    team: 'Cross-squad',
    club: 'Cross-squad',
    icon: BarChart3,
    highlight: true,
  },
  {
    name: 'IA Coach',
    description: 'Des conseils personnalisés pour mieux jouer ensemble',
    free: false,
    premium: 'Basique',
    squadLeader: 'Avancé',
    team: 'Avancé',
    club: 'Avancé',
    icon: Sparkles,
    highlight: true,
  },
  {
    name: 'Audio HD Party',
    description: 'Son cristallin pour tes calls en game',
    free: false,
    premium: false,
    squadLeader: true,
    team: true,
    club: true,
    icon: Mic2,
    highlight: false,
  },
  {
    name: 'Rôles avancés (IGL, Coach, Shotcaller)',
    description: 'Chaque membre sait exactement son rôle',
    free: false,
    premium: false,
    squadLeader: true,
    team: true,
    club: true,
    icon: Shield,
    highlight: false,
  },
  {
    name: 'Export calendrier',
    description: 'Synchro avec Google Calendar',
    free: false,
    premium: false,
    squadLeader: true,
    team: true,
    club: true,
    icon: Calendar,
    highlight: false,
  },
  {
    name: 'Sessions récurrentes',
    description: 'Crée une fois, ça se répète tout seul',
    free: false,
    premium: false,
    squadLeader: true,
    team: true,
    club: true,
    icon: Calendar,
    highlight: false,
  },
  {
    name: 'Dashboard analytics équipe',
    description: 'Heatmaps, fiabilité et tendances de ta squad',
    free: false,
    premium: false,
    squadLeader: true,
    team: true,
    club: true,
    icon: BarChart3,
    highlight: false,
  },
  {
    name: 'Priorité matchmaking',
    description: 'Tu trouves des joueurs 2x plus vite',
    free: false,
    premium: false,
    squadLeader: true,
    team: true,
    club: true,
    icon: Zap,
    highlight: false,
  },
  {
    name: 'Dashboard multi-squads',
    description: 'Vue unifiée de toutes tes équipes',
    free: false,
    premium: false,
    squadLeader: false,
    team: true,
    club: true,
    icon: BarChart3,
    highlight: false,
  },
  {
    name: 'Branding personnalisé',
    description: 'Ton logo, tes couleurs',
    free: false,
    premium: false,
    squadLeader: false,
    team: false,
    club: true,
    icon: Crown,
    highlight: false,
  },
  {
    name: 'API webhooks',
    description: 'Connecte tes outils existants',
    free: false,
    premium: false,
    squadLeader: false,
    team: false,
    club: true,
    icon: Zap,
    highlight: false,
  },
  {
    name: 'Support prioritaire',
    description: 'Une vraie personne te répond vite',
    free: 'Sous 48h',
    premium: 'Sous 24h',
    squadLeader: 'Sous 12h',
    team: 'Sous 8h',
    club: 'Sous 4h',
    icon: Shield,
    highlight: true,
  },
  {
    name: 'Badge exclusif',
    description: 'Montre ton statut dans ta squad',
    free: false,
    premium: 'Violet',
    squadLeader: 'Doré',
    team: 'Bleu',
    club: 'Doré',
    icon: Crown,
    highlight: false,
  },
]

export const TESTIMONIALS = [
  {
    name: 'Alex_Valo',
    squad: 'Squad ranked Valorant 5v5',
    memberSince: 'Membre depuis 4 mois',
    text: "Plus personne n'oublie les sessions. Le coach IA analyse tes habitudes et te propose les meilleurs créneaux pour ta squad. On est passés de Gold à Diamond.",
    avatarType: 'alex' as const,
  },
  {
    name: 'Marie_OW',
    squad: 'Squad ranked Overwatch 2',
    memberSince: 'Membre depuis 6 mois',
    text: "L'audio HD fait la différence en ranked. Les stats détaillées montrent qui clutch le plus — et ça motive tout le monde à se dépasser.",
    avatarType: 'marie' as const,
  },
  {
    name: 'Lucas_RL',
    squad: '3 squads — Valorant, LoL, Rocket League',
    memberSince: 'Membre depuis 8 mois',
    text: "Gérer 3 squads sur différents jeux, c'est le vrai avantage. Un seul dashboard pour tout organiser, zéro session oubliée.",
    avatarType: 'lucas' as const,
  },
]

export const FAQ = [
  {
    q: 'Je peux annuler quand je veux ?',
    a: "Oui ! Tu peux annuler ton abonnement à tout moment depuis ton profil. Tu garderas l'accès jusqu'à la fin de ta période payée. Zéro engagement, zéro frais cachés.",
  },
  {
    q: "C'est quoi la différence entre Premium et Squad Leader ?",
    a: 'Premium est pour les joueurs réguliers qui veulent plus de squads et de features. Squad Leader est pour les capitaines qui gèrent des équipes — avec dashboard analytics, sessions récurrentes, audio HD et rôles avancés.',
  },
  {
    q: "Le tier Team, c'est pour qui ?",
    a: "Le Team est pour les équipes structurées qui ont besoin d'un dashboard multi-squads, de stats cross-squad et de gérer jusqu'à 75 membres. Idéal pour les guildes et clans organisés.",
  },
  {
    q: "Le tier Club, c'est pour qui ?",
    a: "Le Club est conçu pour les structures esport et les organisations qui gèrent plusieurs équipes. Tu as du branding personnalisé, des API webhooks, un support prioritaire sous 4h et une facturation entreprise. Contacte-nous pour un devis sur mesure.",
  },
  {
    q: "Y a-t-il une période d'essai ?",
    a: "Oui ! Tu bénéficies de 7 jours d'essai gratuit sans carte bancaire. À la fin de l'essai, tu choisis ton plan. On offre aussi une garantie satisfait ou remboursé de 30 jours.",
  },
  {
    q: 'Comment demander un remboursement ?',
    a: "Garantie satisfait ou remboursé de 30 jours, sans condition et sans justification. Contacte-nous via le formulaire dans tes paramètres (section Abonnement), et on te rembourse sous 48h par virement. Tu peux aussi passer par le support dans la page Aide.",
  },
]
